name: public

on:
  push:
    branches:
      - public

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: checkout new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b gh-pages
          git config user.name Kei18
          git config user.email keisuke.oku18@gmail.com
          zip -r docs/code.zip ./
          git add docs/code.zip
          git commit -a -m "update public code"
          git push origin gh-pages
