name: public

on:
  push:
    branches:
      - public

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          
      - name: merge
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          target_branch: public
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: add zip file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name Kei18
          git config user.email keisuke.oku18@gmail.com
          zip -r docs/code.zip ./
          git add docs/code.zip
          git commit -m "update public code"
          git push origin gh-pages
